import{a as b,S as v,i as n}from"./assets/vendor-rOMtvQ2t.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const S="51390936-2cac8edb8ccda3d68593e9345",q="https://pixabay.com/api/",E=15;async function f(r,o=1){const e={key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:E};return(await b.get(q,{params:e})).data}const P=new v(".gallery a",{captionsData:"alt",captionDelay:250}),B=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more");function y(r){const o=r.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" />
      </a>
      <div class="info">
        <p><span class="label">Likes</span> ${e.likes}</p>
        <p><span class="label">Views</span> ${e.views}</p>
        <p><span class="label">Comments</span> ${e.comments}</p>
        <p><span class="label">Downloads</span> ${e.downloads}</p>
      </div>
    </li>
  `).join("");B.insertAdjacentHTML("beforeend",o),P.refresh()}function M(){const r=document.querySelector(".gallery");r.innerHTML=""}function h(){m.classList.add("visible")}function g(){m.classList.remove("visible")}function L(){p.classList.remove("hidden")}function c(){p.classList.add("hidden")}const w=document.querySelector(".form"),$=w.elements["search-text"],O=document.querySelector(".load-more");let d="",a=1,u=0;w.addEventListener("submit",async r=>{r.preventDefault();const o=$.value.trim();if(!o){n.warning({title:"Warning",message:"Please enter a search term!"});return}d=o,a=1,M(),c(),h();try{const e=await f(d,a);if(u=e.totalHits,e.hits.length===0){n.error({title:"No results",message:"No images found."});return}y(e.hits),u>15&&L()}catch(e){n.error({title:"Error",message:"Something went wrong."}),console.error(e)}finally{g()}});O.addEventListener("click",async()=>{a+=1,h(),c();try{const r=await f(d,a);y(r.hits),R();const o=Math.ceil(u/15);a>=o?(c(),n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."})):L()}catch(r){n.error({title:"Error",message:"Something went wrong."}),console.error(r)}finally{g()}});function R(){const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
